spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3309/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      #连接池名
      pool-name: DateHikariCP
      #最小空闲连接数
      minimum-idle: 5
      idle-timeout: 1800000
      maximum-pool-size: 10
      #从连接池返回的连接自动提交
      auto-commit: true
      #连接最大存活时间，0表示永久存活，默认180000
      max-lifetime: 1800000
      #连接超时时间
      connection-timeout: 30000
      #测试连接是否可用的查询语句
      connection-test-query: SELECT 1

  redis:
    host: 127.0.0.1
    port: 6379
    #默认操作的数据库
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000ms
        max-idle: 200
        min-idle: 5
    timeout: 10000ms



mybatis-plus:
  #配置mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置Mybatis数据返回类型别名（默认别名是类名）
  type-aliases-package: com.xxxx.seckilldemo.pojo


logging:
  level:
    com.xxxx.seckilldemo.mapper: debug


